### ISSUE TITLE
Ctrl + W as a global shortcut is impractical

### ISSUE THREAD

**Issue by caevee** [Admiral-Billy/Pokerogue-App#1]
Currently pressing Ctrl + W no matter if the game is focused or not will ignore the original use of the shortcut and instead open the wiki. For someone that closes explorer and browser windows very frequently using that shortcut it can be very annoying.

My suggestion:
* Disable shortcuts while application not focused
* Make keybinding rebindable without rebuilding the application

**Comment by Admiral-Billy** [comment]
I shall look into this later
