### ISSUE TITLE
Move saves to diffrent Platform

### ISSUE THREAD

**Issue by M1181121s** [Admiral-Billy/Pokerogue-App#101]
Hey i played on Windows and now want to move to playing on steam deck. What files do i need to move over and where to on linux? I had no Problem finding the state files on windows under %appdata% but dont know what i need form there and where to put it on linux.

**Comment by M1181121s** [comment]
I’m stupid

**Comment by xiibo** [comment]
I’m stupid as well, where did you find it?

**Comment by M1181121s** [comment]
You can export and import in the game itself just open the menu and there is Manage Data. 
Hope this helps

**Comment by xiibo** [comment]
It wouldn't show import data until I switched to offline mode, now it seems to work fine
