### ISSUE TITLE
Quick-mute

### ISSUE THREAD

**Issue by thekillernacho** [Admiral-Billy/Pokerogue-App#102]
Could a hotkey or menu setting be added to mute the game (as one can do similar to muting a browser tab)? Having to change it in the options or through Windows volume mixer is more tedious than it probably should be, and would be helpful when I want to watch something else while playing

Thanks

**Comment by Admiral-Billy** [comment]
Sure, that's something I can look to do when I next update the app. I don't expect that to be too hard.

**Comment by Admiral-Billy** [comment]
I have in fact added this (finally). It'll be in the next release.
