### ISSUE TITLE
Offline mode still greyed out after downloading all game files.

### ISSUE THREAD

**Issue by gameboi4784** [Admiral-Billy/Pokerogue-App#105]
I have downloaded all latest game files on wifi and still cannot enable offline mode.

**Comment by Admiral-Billy** [comment]
Check to make sure all of the files actually downloaded (there should be a "game" folder inside of the "resources" folder in the app). If the app is installed in somewhere like Program Files, the app might also have permission issues extracting the files, in which case running the app as Admin should allow that to work.

**Comment by Vardhman-jain** [comment]
Hi! I had closed the menu in the top corner which allowed me to switch between online and offline mode...and don't know how to get it back...can you pls help

**Comment by gameboi4784** [comment]
> Hi! I had closed the menu in the top corner which allowed me to switch between online and offline mode...and don't know how to get it back...can you pls help

Press alt.

**Comment by Vardhman-jain** [comment]
Thx
