### ISSUE TITLE
Android 11 support

### ISSUE THREAD

**Issue by WillCMcC** [Admiral-Billy/Pokerogue-App#108]
Hello! I'm having trouble getting this running on a device running android 11. It gets up to 100% loading and then crashes. The same thing happens on the web app, for what it's worth. 

I'd love to get this working, if I can be of any assistance let me know.

**Comment by Admiral-Billy** [comment]
Android 11 should be perfectly fine as far as I know. Do you happen to know the rest of your system's specs? Due to it happening on both the web app and the app, that makes me think it might be ram-related or something, but it's hard to say for sure.

**Comment by WillCMcC** [comment]
Ah. Yea that looks likely. 2gbs ram but android is eating quite a bit of it, about 1.2gbs available when I try to boot.  My macbook is able to load the entire thing in under a gig according to the chrome task manager, but it does jump sometimes so maybe that is occurring on first boot.

**Comment by WillCMcC** [comment]
well this seems to be solidly a "me issue" -- if you don't have any magic incantations I can try, I'll close this out 😂

**Comment by Admiral-Billy** [comment]
Yeah there's not really much I can suggest unfortunately in terms of fixes :(

It's pretty much just a matter of "it works" or "it doesn't work" due to the way everything operates.
