### ISSUE TITLE
idk how to play offline by downloaded files on mobile

### ISSUE THREAD

**Issue by MS55479** [Admiral-Billy/Pokerogue-App#110]
I wanna play pokerogue by downloaded files on mobile app, but when I run pokerogue offline, I cannot click offline button. Is there any solution for this?
![Screenshot_20240629-204706_PokeRogue Offline](https://github.com/Admiral-Billy/Pokerogue-App/assets/174189754/ed21a0bf-1658-4a62-adca-2053e2e6e22d)

**Comment by Admiral-Billy** [comment]
You need to download files first with one of the two buttons below it.

**Comment by MS55479** [comment]
when I click 'play offline' button bt downloaded files in that way, game stops.
