### ISSUE TITLE
Add PokeRogueModLoader support

### ISSUE THREAD

**Issue by MikeyTheA** [Admiral-Billy/Pokerogue-App#112]
Hello!

I've been working on a [mod loader for PokeRogue](https://github.com/MikeyTheA/PokeRogueModLoader), and was wondering if it would be possible to add support for switching to this in the app. The mod loader is available [here](https://mokerogue.net), which is connected to a server I'm running myself, so it does not affect official servers. It is also possible to run it offline by cloning the repository.

**Comment by Admiral-Billy** [comment]
Oh yeah, it'd be super easy to allow switching to it. You could even just make it your own launcher if you wanted to by switching the URL that the app connects to in main.js. Next time I update the app I'll see what I can do; adding a setting in the settings menu and then using an if/else check for which server to connect to should be super easy overall.
