### ISSUE TITLE
shiny sprites missing

### ISSUE THREAD

**Issue by JustXTaiga** [Admiral-Billy/Pokerogue-App#113]
Heya, i dont know if this is a mobile issue or a generall pokerogue one, but in the mobioe offline version i have a tier 3 shiny timburr but i only see his standart sprite (Samsung Galaxy S9+)
![Screenshot_20240704-082721_PokeRogue Offline](https://github.com/Admiral-Billy/Pokerogue-App/assets/174685719/a04691a8-e42d-4737-b8a3-01bf6f19e57b)

**Comment by ufohoax** [comment]
this also happens with gorgeist, provided screenshot. rattata's red shiny, golurk's red shiny, and even the rivals blue shiny rayquaza. gorgeist is a regular, and pumpkaboo shines like normal, it's evolution does not. it's quite odd.
![Screenshot_20240627_125141_PokeRogue Offline](https://github.com/Admiral-Billy/Pokerogue-App/assets/174751420/5a289243-9f0d-4db0-9061-8a68acbc4006)


![Screenshot_20240704_184501_PokeRogue Offline](https://github.com/Admiral-Billy/Pokerogue-App/assets/174751420/902ecd24-c149-4d2c-b4ab-d3c7aa6c4c7f)
![Screenshot_20240704_184518_PokeRogue Offline](https://github.com/Admiral-Billy/Pokerogue-App/assets/174751420/71c65f6e-0376-459f-aae8-d9c8806c06e3)

**Comment by Admiral-Billy** [comment]
I believe this is a general PokeRogue issue, so there's not much I can do on my end.
