### ISSUE TITLE
Controller issue

### ISSUE THREAD

**Issue by Cephyr0** [Admiral-Billy/Pokerogue-App#115]
Since last week wednesday controllers seem to not wok properly anymore,  in particular the  controlelrs are recognized correctly by the  game , face  buttons  do work  but not the d pad and neither analog stick if available

The Controller itself still work fine in every other application. I tested 2 other ones which also didnt work properly

i tested 3 Controllers 8bitdo m30, 8bitdo pro2 and hori fighting commander octa.
i tested on 3 different platforms windows, linux, android (on android i didnt test the hori). 
i  tested  both via Bluetooth and via USB
i tested both browser and app. interms of browser i also tested 3 different ones : Chrome, Firefox and Edge

it  was always the  same: every controller is recognized and mapped correctly except for dpad which doesnt work  at all and is impossible  to remap.

the only combination  where it works properly was on my windows PC with the pro 2 connected via 8bitdo USB  connector 2

i didnt test my xbox controller at all since its partially broken anyways ( face buttons  dont react sometimes) but  i might , since here i can also test bluetooth  , usb and wireless connection via MS Wireless connector (or whatever its called).

i suspect it might be sth in the game itself but who knows.

Edit: Before Said Wednesday last week it worked flawlessly via bluetooth and USB with every controller (  though  i only used the  m30 , pro2 then; the m30 is awsome for mobile/  travveling causeits size)

**Comment by Cephyr0** [comment]
still no solution, guess there cant be done anything

**Comment by pearagit** [comment]
ive had this before, a combination of uninstalling the app, deleting the app data folder(s), and repairing the controllers worked

**Comment by Cephyr0** [comment]
unfortunatley that didnt fix it for me. i might post the problem on the discord or github page of the main game. Since this apps creator didnt answer  i might have chosen the wrong place after all. Though i play exclusivley through  this app and it   works for me flawless apart from the Blue tooth and specific controller problem.

**Comment by Admiral-Billy** [comment]
Apologies, this is something I missed. I *think* this is a game-specific issue of some kind, but I'm not 100% sure. If anyone has extra details about it, I'll see what I can do.

**Comment by Cephyr0** [comment]
sorry for  coming back really  late forgot completly stuff, RL was wild.
Anyways problem has been solved since the update after the admiral wrote  last  here
dunno who or what fixed  it but now  since then everything works great
