### ISSUE TITLE
Virtual "A" Button latching on after data import on Android.

### ISSUE THREAD

**Issue by Ghostsuit** [Admiral-Billy/Pokerogue-App#121]
On android, after selecting the file that should be imported there's a chance that the Virtual A button will not get released. Pressing A again seems to unlatch the button. Happens when importing both slots and full save files.

**Comment by Admiral-Billy** [comment]
I've tried to fix this issue in a couple different ways, but can't really find an elegant solution for it. If anyone has a solution, please let me know!

**Comment by seanrmon** [comment]
I managed to use the following to fix this on the android version:
`webView.loadUrl("javascript:this.Phaser.Display.Canvas.CanvasPool.pool[1].parent.scene.inputController.loseFocus()");`
This fix will also prevent any inputs from getting latched when the app is paused for any other reason
