### ISSUE TITLE
Add option to use the beta version of PokeRogue

### ISSUE THREAD

**Issue by Ghostsuit** [Admiral-Billy/Pokerogue-App#122]
Would be fantastic to use upcoming features. Good predicter of compatibility issues when beta features get ported onto the main server.

Might be similar to:
https://github.com/Admiral-Billy/Pokerogue-App/issues/112

**Comment by Admiral-Billy** [comment]
I'll toss that into the next update, since it's really easy to do.

If you want to do it ahead of schedule, you can just change the url in main.js from the main website to the beta one, and build the app.

**Comment by Admiral-Billy** [comment]
Alrighty, I have this added for the next version of the app.
