### ISSUE TITLE
Links at top of screen

### ISSUE THREAD

**Issue by NotANumberNaN** [Admiral-Billy/Pokerogue-App#123]
It seems like within the past day 4 links have appeared at the top of the screen, linking to the Privacy Policy, Cookie Disclaimer, Terms & Conditions, and Acceptable Use Policy. Clicking on them brings to to what you would expect, but there is no way out of them other than restarting the app. 
![Screenshot_20240729-180010](https://github.com/user-attachments/assets/f78d28c0-e62b-49f5-a4a2-41d0fa25f8cf)
![Screenshot_20240729-180016](https://github.com/user-attachments/assets/293b7e15-b556-4022-8ed5-c35fbe9a89c4)
![Screenshot_20240729-180022](https://github.com/user-attachments/assets/dcadf18b-22ea-4092-9a15-08788b984634)
(Sorry if I misformatted the issue or left information out, I'm not used to using GitHub and I'm on mobile.)

**Comment by Admiral-Billy** [comment]
I've got this fixed for the desktop version at least in an upcoming release, but haven't looked at the mobile version yet.
