### ISSUE TITLE
game opens to blank screen

### ISSUE THREAD

**Issue by dandydanish** [Admiral-Billy/Pokerogue-App#127]
![Untitled](https://github.com/user-attachments/assets/05350053-af4e-49ea-888f-9727d1965f8b)

On both the windows and android version

**Comment by Admiral-Billy** [comment]
This is indeed an issue with the latest update, but I'm not sure how to fix it personally. It's related to some files not being loaded correctly; if anyone can submit a PR for it I'd definitely integrate it!

**Comment by EternalWraith** [comment]
Issue seems to be caused by a failure to find the manifest.json file; it seems to be looking in the C drive and not wherever it should be looking for it

**Comment by Liu7i-67** [comment]
The problem is caused by the animation, which requires some processing of the AnimationConfig when it is packaged offline, and it feels like someone wrote a bug

**Comment by Admiral-Billy** [comment]
Someone submitted a PR that does successfully fix this issue; update the app and you should be good to go.

**Comment by Liu7i-67** [comment]
Will do, thanks!

William Burleson ***@***.***> 于2024年8月19日周一 16:45写道：
