### ISSUE TITLE
How to Import Save File ? (data.prsv)

### ISSUE THREAD

**Issue by Le-Iceberg** [Admiral-Billy/Pokerogue-App#13]
Hello, 
First of all, thank you for this local and offline port of Pokérogue, it's exactly what I was looking for ^^.

j'ai juste une question, j'ai récupérer sur le site mon fichier data.prsv mais je ne sais pas comment le réimporter et toutes mes recherches sur internet (reddit et autre) n'ont donné rien de clair.

How can I recover my save from my account and reimport it so that I can play locally with everything I've unlocked and my progress?

If possible, I'd like the method for Windows and Android (mine is root).

Edit 05/08/2024 : Ok on android it's works !
I think it's a bug on PC app that don't show import button i don't know why but i report this for you
![image](https://github.com/Admiral-Billy/Pokerogue-App/assets/47919634/1282c0a0-8f68-4282-9b4b-df2935fae2bd)

and on my android:
![Screenshot_2024-05-08-23-18-53-558_com example pokerogueoffline](https://github.com/Admiral-Billy/Pokerogue-App/assets/47919634/7c2b310a-4b9f-496a-b662-3ee0f08b11b2)

Thank you in advance for your help!

Have a nice day!

**Comment by Axelrasha** [comment]
It's seems that `window.location.hostname = ''`
And in the code of online pokerogue project, they block the importdata feature (to prevent cheating on the "official" server) by making a condition on window.location.hostname
if `window.location.hostname` is different from `'localhost'` (which is the case here), you cannot import data.

So 2 possibilities:

1. Find a way to have `window.location.hostname = 'localhost'` in Pokerogue-App
2. Asking in Pokerogue project to change the condition to make `window.location.hostname = ''` another case of local game

Unfortunately, I didn't find any workaround for the moment

**Comment by Le-Iceberg** [comment]
Strange to propose to export data if we can't import them ? 
and in android it's work perfectly as you can see on the screen

But ok i guess

**Comment by Axelrasha** [comment]
Seems fixed : https://github.com/pagefaultgames/pokerogue/commit/94da7838f81b2da2d852fd0e5ea870fc73af7b4b

**Comment by Le-Iceberg** [comment]
Oh! you're right I updated the windows application for offline and it's back ^^.

thanks for your answers!
I confirm ! it works =D

**Comment by Nezumi-exe** [comment]
I still don't see the import save option in my menu?
![image](https://github.com/Admiral-Billy/Pokerogue-App/assets/4240036/a2cb8321-d263-418d-9452-ec9d055b8fc4)

**Comment by Le-Iceberg** [comment]
I see that the online site also doesn't work. 
so I still think it's a site bug
![image](https://github.com/Admiral-Billy/Pokerogue-App/assets/47919634/0653b7db-cdd8-4021-9c35-6ff1eb1909bd)

**Comment by Le-Iceberg** [comment]
I see that the online site also doesn't work.
so I still think it's a site bug
![image](https://github.com/Admiral-Billy/Pokerogue-App/assets/47919634/a79c7484-3cdf-4b73-b01e-782956f29123)

**Comment by InfernoPheonix** [comment]
gay
