### ISSUE TITLE
Android version open to a blank screen 

### ISSUE THREAD

**Issue by RoudiKing** [Admiral-Billy/Pokerogue-App#137]
![Screenshot_20240902-163357](https://github.com/user-attachments/assets/83ee488b-1e06-4949-81df-367fbb834a45)

**Comment by Admiral-Billy** [comment]
Are you on the latest version of the app (not the game files)? This is a bug I fixed on newer versions of it in theory.

**Comment by RoudiKing** [comment]
Yes i installed the lastest update of the app

**Comment by Dmzpra** [comment]
Mine keeps getting connection errors even though the internet is running smoothly
![Screenshot_20240914-165330](https://github.com/user-attachments/assets/a1562ae7-d163-4312-9d9b-e7aa599c1e31)

**Comment by Admiral-Billy** [comment]
I'm going to close this for now since I don't really have much more information to go off of; just make 100% sure that the app is updated, and I'd double check that your device can run the browser version of the game as well, just in case it's not the app's fault.
