### ISSUE TITLE
Game hangs after a battle

### ISSUE THREAD

**Issue by kvndrxck** [Admiral-Billy/Pokerogue-App#138]
After beating a black belt, my game hangs after selecting an item from the shop. The screenshot is of the errors that pop up when that happens
![Capture](https://github.com/user-attachments/assets/0d9f0f53-e0b3-4c6a-985f-e81e03966d63)

**Comment by Admiral-Billy** [comment]
I thought this was a bug I'd fixed in the past, but maybe it's coming back for some reason. If anyone can find a fix, that would be appreciated; my previous fix was to just create a generic blank file to use whenever an animation is missing, but maybe that stopped working for some reason?

**Comment by Jundude** [comment]
I've found a work around by exporting the session data from my steam deck (running the Linux version) to my phone running the android version. I'm able to get past the freezing point, then export/import the session data back. It's a little cumbersome, but beats losing a run.

**Comment by Admiral-Billy** [comment]
I believe this issue is fixed in the beta (and thus will be fixed relatively soon on the main branch).
