### ISSUE TITLE
Offline games only save to slot 1

### ISSUE THREAD

**Issue by Reika154** [Admiral-Billy/Pokerogue-App#14]
In offline mode, regardless of which save slot is selected on a new game, the first slot is always the one the game saves to.

**Comment by Reika154** [comment]
Scratch that, just updated, and now multiple slots work.

**Comment by Admiral-Billy** [comment]
Oh I see; I'll tell sam about this one.

**Comment by Zarlokh** [comment]
https://github.com/pagefaultgames/pokerogue/commit/f540b7d17fa01a6f43e3f9ba237f92c682e2fe9b
