### ISSUE TITLE
I want to modify an offline APK!

### ISSUE THREAD

**Issue by Nonbts** [Admiral-Billy/Pokerogue-App#142]
First, I'd like to express my gratitude as an APK user.

I'm currently playing the offline version of a game. As I progress through the levels, I receive one Master Ball per floor, but I want to modify the code so more Master Balls appear. However, no matter how hard I look, I can't seem to find the Android data folder. Could you tell me how to do this?

Since I'm currently unable to use a computer, I need to modify it through mobile. If you can explain the method, I'll definitely give it a try.

**Comment by Admiral-Billy** [comment]
Sometimes the default file explorer that comes with the device won't actually let you browse *all* of the files; I don't know if it's specifically an app issue or a mix of app + device issue, but sometimes getting into the android data folder is a pain.

In either case, if you *can* get into it, you should be able to go into a folder that's something like "com.pokerogueoffline" and then go into a game folder and find the game's files there, but the app uses compiled files so everything is going to be jumbled up in an unreadable mess in one big index.js file. The workaround for the truly dedicated would be using a computer to edit the source code, then building it on PC, then transfering that over to Android, but when that's not an option you don't really have a choice but to try and deal with the jumbled code.

In this case you'd be looking for some sort of modifier weight for the master ball, but I can't really pinpoint that stuff for you, especially in the compiled file; you'd just have to do some digging with a text editor and hope for the best.
