### ISSUE TITLE
Offline mode greyed out in my app, won't work!

### ISSUE THREAD

**Issue by RecoveryISCool** [Admiral-Billy/Pokerogue-App#144]
Hey there Billy & friends, 

So I have tried to download the files for offline use and it'll do that, but the offline mode option under the settings won't un-grey itself. Should I just reinstall? I am unsure how to get the offline mode to not be greyed out. I am on a windows Surface 4, had no problems before but I also didn't know how to get to offline mode until this week and I tried to and it won't allow me. 
Thanks!
-Charles

**Comment by Admiral-Billy** [comment]
If it's still greyed out that's usually because the app hasn't detected that the files are actually downloaded, so either it's erroring out or you may not be letting it complete. If you want to confirm that the game's files are there, check the resources folder and see if you have a game folder; if not, the game isn't downloaded.

**Comment by RecoveryISCool** [comment]
What does the game folder look like? You mean the destination where I unzipped the files, correct? I did let it download multiple times until it was completed, and it still has remained gray.

**Comment by RecoveryISCool** [comment]
I checked the resource folder and there is no game saved, so I have no clue how to fix that!

**Comment by Admiral-Billy** [comment]
Yeah, it's hard to say exactly what's going on in that case. If you want to try a manual download, the app has the github for game files in the about/links section at the top; you could download the game.zip and stick it into that resource folder and it'd probably show up with future launches. 
![image](https://github.com/user-attachments/assets/40053231-7bdf-42f2-9761-bb4223b0f75f)

**Comment by RecoveryISCool** [comment]
I'll give it a try now.

**Comment by RecoveryISCool** [comment]
I did as instructed (I think, because it did download the files WAY faster this time) and then let it download the files/extract them and the same with Futuba's build and nothing, it's still grayed out.

**Comment by Admiral-Billy** [comment]
There shouldn't really be anything wrong with it at this point, assuming it is actually in that folder. If you did want to try starting from scratch, it's as simple as deleting the game's folder and redownloading the latest release from this Github repo. But yeah, I really don't know what's going on if the game folder is in the correct location and the app isn't detecting it; that hasn't been an issue before as far as I know.

**Comment by RecoveryISCool** [comment]
![whatmyfileslooklike](https://github.com/user-attachments/assets/15a2fbf1-38b1-4e33-9e27-d2df79c63192)

**Comment by Admiral-Billy** [comment]
I think you could just delete the whole PokeRogue folder and then redownload it from here.

Looking at this image, I think what happened before is that the files in the zip should be *in* a game folder, and not the resource folder itself. Once you've redownloaded the app, try creating a game folder in this resources folder and dropping the game.zip into there, and *then* unzipping it. That should make sure all the files are in the right place and then in theory the game will be able to pick up on that.

![image](https://github.com/user-attachments/assets/74cac846-e3dc-4bf9-a539-eef40ecca62e)

**Comment by RecoveryISCool** [comment]
Will attempt and update with results!

**Comment by RecoveryISCool** [comment]
IT WORKED! Thanks so much!!!
