### ISSUE TITLE
Impossible to play dailyrun in offline mode

### ISSUE THREAD

**Issue by Axelrasha** [Admiral-Billy/Pokerogue-App#15]
When playing offline mode, it's impossible to play dailyrun, the game freeze immediatly, cause it failed to fetch files from http://localhost:8001 .
I have a fix for this, but don't know how to get/ask for the permissions to push a bugfix branch?

EDIT : With my fix, I don't have the same dailyrun in local that on the server. So not so sure anymore

**Comment by Axelrasha** [comment]
With my fix, I don't have the same dailyrun in local that on the server. So not so sure anymore

**Comment by Admiral-Billy** [comment]
Ideally whatever fix you have for it should be referred to Sam (as a PR on the main pokerogue branch) so that my code can snag stuff from it! But yeah this is a known issue for the time being at least.

**Comment by Axelrasha** [comment]
But my fix is on this project
```diff
diff --git a/preload.js b/preload.js
index 8f9c714..08f4253 100644
--- a/preload.js
+++ b/preload.js
@@ -22,7 +22,7 @@ ipcRenderer.on('offline-mode-status', (event, status) => {
 // Override the global fetch function when in offline mode to fix broken move issues (and more?)
 const originalFetch = window.fetch;
 window.fetch = async (url, options) => {
-  if (isOfflineMode && url.startsWith('./') || url.startsWith('../')) {
+  if (isOfflineMode && ( url.startsWith('./') || url.startsWith('../') || url.startsWith('http://localhost'))) {
     const gameDir = getGameDirectory();
     const filePath = path.join(gameDir, url.split('?')[0]);
     console.log("Fetching file:", filePath);
```

**Comment by lelouchTzero** [comment]
is daily run still broken?

**Comment by Admiral-Billy** [comment]
This one will be resolved in a PR soon, whenever that gets merged.
