### ISSUE TITLE
Playing offline leads to Black screen(Android)

### ISSUE THREAD

**Issue by Lebos808** [Admiral-Billy/Pokerogue-App#151]
With the new Halloween update, when trying to load the offline version of the game it goes to a black screen and doesn't load game. I have tried clearing cache, restarting device, and downloading files from server, but no luck.

**Comment by Admiral-Billy** [comment]
This seems to be an issue on the devs' side, I'm not sure yet if I'll have to release an app update to fix it or if it'll be fixed on their end though.

**Comment by Admiral-Billy** [comment]
Alright, based on what a dev said this should be something they'll fix soon (although it could be anywhere from hours to days).

**Comment by Lebos808** [comment]
Just to clarify, the online version works just fine. Only the offline version is bugged

**Comment by Admiral-Billy** [comment]
Offline is good to go again, thanks to a PokeRogue update.
