### ISSUE TITLE
Nex Dex

### ISSUE THREAD

**Issue by Souhailkudo** [Admiral-Billy/Pokerogue-App#157]
Ydarissp made his dex private, so the dex Ctrl+D links to no longer works. Can you change that link to the new dex made by the game devs ? The new dex can be found at [https://wiki.pokerogue.net/starters:pokedex](https://wiki.pokerogue.net/starters:pokedex) according to the official discord. Thanks in advance for this and for all the work you put in this handy project.

**Comment by Admiral-Billy** [comment]
oh yeah, good point; I'll do that real quick.
