### ISSUE TITLE
Freezing game onfline

### ISSUE THREAD

**Issue by NarcisoUNK** [Admiral-Billy/Pokerogue-App#18]
Hello i having a problem , my game is freezing randomly i already restart the game and reload save but is bugged.
Its always when i take a item, my game freezes.

I already reset 3 runs because of this some1 has idea how to fix it?

![image](https://github.com/Admiral-Billy/Pokerogue-App/assets/133000193/e28ea372-ed95-4436-bd26-76656e18ecb3)
![image](https://github.com/Admiral-Billy/Pokerogue-App/assets/133000193/97f27633-c2b2-460a-b0c1-19c369456f29)
![image](https://github.com/Admiral-Billy/Pokerogue-App/assets/133000193/d3aa3cb2-64a9-4148-b8a3-0983072a9acf)

**Comment by Axelrasha** [comment]
Have you taken the latest version? Your issue is supposed to be fixed in v2.0.1. This is the link for the latest build (2.1.1) https://github.com/Admiral-Billy/Pokerogue-App/releases/tag/v2.1.1

If it is already the case, can you open you devtools, go to console, and screen the errors?

**Comment by artman41** [comment]
It could be a recurrence of #12 - I've posted a comment [on there already](https://github.com/Admiral-Billy/Pokerogue-App/issues/12#issuecomment-2105328433) with evidence that it's still a problem

@NarcisoUNK have you got a save file that you can replicate the issue with?

Failing that, if you follow these steps, you'll be able to take a screenshot of the error

1. Press `F12`
2. Go to the `Console` tab
![image](https://github.com/Admiral-Billy/Pokerogue-App/assets/5568965/36c34288-d6ed-4c0f-ab62-b1c8dd87491b)
3. Screenshot (Shift+Win+S) the application (including the text in the console tab) so you have a picture like this
![image](https://github.com/Admiral-Billy/Pokerogue-App/assets/5568965/532b12ca-9ca8-4164-8cbb-5a3c10c97f63)

**Comment by NarcisoUNK** [comment]
I have to play more again because i restarted the run,i will try today to get same round i got there to replicate the problem.
Probally when i got the issue again i print here once again


Thank you

**Comment by evilmaran** [comment]
Game keeps freezing after battles. Updated in the way that the screenshots above showed, running as admin.

console screenshot
https://prnt.sc/-f8jdjiPObAn
Failed to fetch error.

**Comment by artman41** [comment]
> Game keeps freezing after battles. Updated in the way that the screenshots above showed, running as admin.
> 
> console screenshot https://prnt.sc/-f8jdjiPObAn Failed to fetch error.

 could you export that save and upload it to this issue @evilmaran?
 
 You may need to suffix the save with `.txt`

**Comment by evilmaran** [comment]
sure here it is
[data.prsv.txt](https://github.com/Admiral-Billy/Pokerogue-App/files/15287605/data.prsv.txt)

**Comment by Admiral-Billy** [comment]
Is this in online mode? It's fetching URLs instead of files, and the servers are having issues that'll cause stuff like this to happen.

**Comment by NarcisoUNK** [comment]
Hello once again i got here a print from a console on other run, i am doing

![image](https://github.com/Admiral-Billy/Pokerogue-App/assets/133000193/29f62127-ff03-4a98-99c3-89ba6e05feae)

**Comment by evilmaran** [comment]
> Is this in online mode? It's fetching URLs instead of files, and the servers are having issues that'll cause stuff like this to happen.

yeh it is, didnt know it was server related, swapping to offline today.

**Comment by Admiral-Billy** [comment]
> Hello once again i got here a print from a console on other run, i am doing
> 
> ![image](https://private-user-images.githubusercontent.com/133000193/330015547-29f62127-ff03-4a98-99c3-89ba6e05feae.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU2NzI1MTIsIm5iZiI6MTcxNTY3MjIxMiwicGF0aCI6Ii8xMzMwMDAxOTMvMzMwMDE1NTQ3LTI5ZjYyMTI3LWZmMDMtNGE5OC05OWMzLTg5YmE2ZTA1ZmVhZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxNFQwNzM2NTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mODI3NjRjNzE3OGE0M2M4ZjMxZmM1YTM1NWVkMDg2NTNlNGNhNzBkZWFiZTcwNzFiM2Y3MjM3NGYzMDNjOTJmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.u166gyGUZaqGgPAnUErzNm6qrLqag9Jcv0yz1bmeGbc)
> 
> Update: I installed the updates i played around 15 waves more and he crashed once again
> 
> ![image](https://private-user-images.githubusercontent.com/133000193/330018702-ff645567-a76e-4c57-8658-0083659a36e5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU2NzI1MTIsIm5iZiI6MTcxNTY3MjIxMiwicGF0aCI6Ii8xMzMwMDAxOTMvMzMwMDE4NzAyLWZmNjQ1NTY3LWE3NmUtNGM1Ny04NjU4LTAwODM2NTlhMzZlNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxNFQwNzM2NTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xM2RkODFiMGY2NzBlODQ3NGVlNjM2Zjg5MzI2OTY1ZjE1YzI3OTdiYjAyMzRmNmU2YjhmMWE5YjA2M2JiNWNkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.D1UW0ygbahw-rnomShI-EnFr7BCBGh8Q9UrLJr7SYFw)

This one I can't really confirm without more information, e.g. offline/online mode, and the latest version of the app you've install from GitHub. My hunch would be that it's an older version of the app (slightly) since it doesn't have the debug text I put in to track down some of these issues, and/or it's in online mode so they don't show up, but I can't confirm either of these.

**Comment by NarcisoUNK** [comment]
Like i said on title is on offline mode , and yes is the latest version because i used the option of Download latest files for offline.

**Comment by Admiral-Billy** [comment]
I'm talking about the latest version of the *app*, not the game.

**Comment by Admiral-Billy** [comment]
For now I'm going to assume this issue was resolved; I haven't gotten any recent reports of it that updating the game + app hasn't fixed.
