### ISSUE TITLE
Cant export data from android version

### ISSUE THREAD

**Issue by shinvictor728** [Admiral-Billy/Pokerogue-App#20]
This might just be something that is supposed to not be working atm but just in case. I cant export data or session data from the android pokerouge apk. Just pops up with a error that the file can't be downloaded.

**Comment by Admiral-Billy** [comment]
This is a known issue atm; I think it has to do with permissions, but I need to figure out what's going on first before I can fix it.

**Comment by Admiral-Billy** [comment]
Alright, so while this is definitely an issue still, there is at least a workaround for it you can do (copy-pasted from a discord message I sent):

For anyone on the Android version, there is a known issue where exporting and/or importing may not work correctly. Until a proper solution is found, this work-around may work by giving it the permissions it's supposed to request:

In your settings, go to apps -> 3 dots menu at the top right -> special access -> all files access (you might also be able to just search to get to here), and then find PokeRogue Offline in the list and give it the permission. This should let it read/write as expected, and I pinkie promise that it's not going to do anything sussy wink wink nudge nudge.

**Comment by GDKampfer** [comment]
Platform: Android and PC offline version on v2.3.3 and latest game file update at time of this post.

I also had problems with exporting android saves (download failed), but something changed from the recent updates. Exporting both data and session on android now says that "file was downloaded in downloads folder" but only the data.prsv saves to the download folder. Importing this data.prsv into the PC offline version results in a text hidden by the leaderboard and ssettings UI but I'm guessing says save couldn't be loaded. 
Renaming the data.prsv from android to data_Guest.prsv loads the save correctly. 
So it means that save transfers are working but session saves cannot transfer.

**Comment by Admiral-Billy** [comment]
Oh yeah, so funny story about that, but *every* file you save on the Android version saves as a "data.prsv" due to the way I had to actually implement that. I can probably fix that, but your session saves should actually be exporting just fine as long as you give them the proper name heh.

**Comment by Pressecitrons** [comment]
Any other work around ? I can't modify the permissions of pokerogue to add the files accesss permission. I also can't find the saves folder on Android to manually transfer my save from phone to phone.

**Comment by Admiral-Billy** [comment]
There's not another workaround that I know of at least, and I still haven't found a proper solution for this. The Android code is open source now though if anyone else spots the issue.

**Comment by Admiral-Billy** [comment]
Hey what do you know, I fixed it! I needed to rewrite my permissions code a bit so it should properly request those permissions in the next version of the app when it's out.

**Comment by Pokion1027** [comment]
Whats the name of exported acc data?

**Comment by odejuanknobe** [comment]
> I think the WRITE_EXTERNAL_STORAGE would work instead if MANAGE_EXTERNAL_STORAGE I tested on 2 devices (1 Android 10 and Android 13) and it won't work only on the Android 10 phone

What us the file pathnane to find the place to enter it?
