### ISSUE TITLE
Audio plays even after closing app

### ISSUE THREAD

**Issue by Wyxaldir** [Admiral-Billy/Pokerogue-App#21]
Even after exiting the app or locking my phone the audio keeps on playing until I completely close the app.

**Comment by Admiral-Billy** [comment]
Ah, I noticed that one myself. I don't think it has a proper standby mode at the moment. I'll see what I can do when I get back to the Android app.

**Comment by Admiral-Billy** [comment]
This should finally be fixed when I next update the app.

**Comment by Admiral-Billy** [comment]
Actually, when I say fixed, I mean that this causes other problems and apparently it's just not a thing you can do with web pages on Android, so I guess it's going to stay a "feature".
