### ISSUE TITLE
Offline mode erroring out

### ISSUE THREAD

**Issue by travbp** [Admiral-Billy/Pokerogue-App#22]
I'm hard locked at a spot in my run due to the following errors. I'm running the latest 2.1.1 release on my Steam Deck with the recommended launch options.

![image](https://github.com/Admiral-Billy/Pokerogue-App/assets/112346662/1803eec0-6930-4d83-beb1-cfbb03fd9e52)

**Comment by Admiral-Billy** [comment]
Make 100% sure you're on the latest version; someone else had the same issue claiming to be on the newest version but once they deleted + redownloaded it fixed itself heh

Let me know if that still happens though, I can 100% confirm the issue with failed json fetches is resolved in the newest version unless something weird is going on.

**Comment by Admiral-Billy** [comment]
Actually, there still *was* a bug. As it turns out, I only checked for offline mode after the game's been reloaded at least once, so if you start the game from offline mode off the bat it wouldn't work. Fixed!

**Comment by travbp** [comment]
Thank you!! I'll give it a shot here in a sec. To update the app, do I export my data, delete and redownload the Pokerogue app files, download offline files, and reimport my save data. Or is there an easier way?

**Comment by travbp** [comment]
Did this ^ and it works perfectly now. Thanks again!
