### ISSUE TITLE
Feat: About button

### ISSUE THREAD

**Issue by artman41** [Admiral-Billy/Pokerogue-App#24]
I think an 'about' button which lists the current version of the downloaded offline files might help to work out if the bugs people are experiencing are new or not

It could also be nice for there to be a version check on there that compares against the latest github tag

**Comment by Admiral-Billy** [comment]
Could definitely be nice, it'd help if the game itself kept track of its own version though lol

**Comment by Admiral-Billy** [comment]
Well well, it seems like you've done this for me, so I guess I'm closing this now heh
