### ISSUE TITLE
Freeze at the end of a classic run

### ISSUE THREAD

**Issue by travbp** [Admiral-Billy/Pokerogue-App#25]
I seem to have encountered a similar freeze (failed fetch) to my other [issue](https://github.com/Admiral-Billy/Pokerogue-App/issues/22) after switching to the latest release. This time it's freezing at the end of a classic run.

Environment:

Steam Deck
Release 2.2.1
- updated from 2.1.1 by exporting save, deleting all app files in the extraction folder, extracting 2.2.1 linux zip, downloading offline files, switching to offline mode, and importing my save that I was playing on a previous release. Namely, I didn't delete any other files if they are cached somewhere outside of the extraction folder.

![image](https://github.com/Admiral-Billy/Pokerogue-App/assets/112346662/10c0393d-079b-4493-8999-2f7e99906df3)

**Comment by AmineBenSlimanee** [comment]
i got the same problem 

![image](https://github.com/Admiral-Billy/Pokerogue-App/assets/58090140/e1c17573-9554-40f9-a239-0c310067143b)

**Comment by rtawil** [comment]
I am encountering the same "Failed to fetch" issue on a fresh install of the latest release (imported data and session).

**Comment by Admiral-Billy** [comment]
Yeah I can confirm that Sam attempted to fix a similar issue (and did not get this one) so I'll be trying to see if I can get a PR in to fix it at some point once I find the issue.

**Comment by Rorkiful** [comment]
I have the samedi bug on Android device, offline but i do regular updates.
I will keep the save and hope you can resolve this one day 😂

**Comment by travbp** [comment]
> I have the same bug on Android device, offline but i do regular updates.
> 
> I will keep the save and hope you can resolve this one day 😂

If your save is in slot 1, make sure to export it and reimport it into a higher slot. There's a Pokerogue bug where failing a run in another slot will always clear the save in slot 1, which isn't always the save of the run that actually failed. Wiped my wave 200 save that way :(

**Comment by Rorkiful** [comment]
> > I have the same bug on Android device, offline but i do regular updates.
> > I will keep the save and hope you can resolve this one day 😂
> 
> If your save is in slot 1, make sure to export it and reimport it into a higher slot. There's a Pokerogue bug where failing a run in another slot will always clear the save in slot 1, which isn't always the save of the run that actually failed. Wiped my wave 200 save that way :(

Thanks, didn't know and failed other runs after without this bug but just to be sure i'll export it 😉

**Comment by Admiral-Billy** [comment]
There's a fix for this in the PRs, although I'm not sure exactly when it'll be merged into the main game.

**Comment by Rorkiful** [comment]
I Hope it will be soon 'cause i have a second run in this state 😂
Guess i'll do some endless until the release 😂
![Screenshot_2024-05-14-10-57-43-449_com example pokerogueoffline](https://github.com/Admiral-Billy/Pokerogue-App/assets/169688572/5fe17bf6-a6c2-487b-b4fd-ce4c1a3e1447)

**Comment by Admiral-Billy** [comment]
It has indeed been fixed as of now.

**Comment by Socialblurr** [comment]
> It has indeed been fixed as of now.

Is this going to be in the next APK drop?

**Comment by travbp** [comment]
Thanks @Admiral-Billy, you're awesome!
