### ISSUE TITLE
Window not centered on steam deck gaming mode

### ISSUE THREAD

**Issue by Eduardboon** [Admiral-Billy/Pokerogue-App#26]
When opening the app on Steam Decks gaming mode the window starts at the top but doesn’t draw all the way to the bottom and doesn’t center itself on the screen. 

I don’t know how to fix this myself but enabling fullscreen did not fix it, neither did enabling a custom resolution.

**Comment by Admiral-Billy** [comment]
I haven't actually figured out what causes that to happen myself. On my Steam deck at one point it wasn't centered, but now it is. In either case, using the darker background setting should work just fine in terms of immersion, especially on the OLED.

**Comment by Eduardboon** [comment]
Agreed, it’s completely playable! Desktop mode has the same issue suddenly, even in a browser. So I guess it could just be a bit random.

**Comment by Admiral-Billy** [comment]
It seems that there's going to be a centered option added to the game soon, so regardless of what caused the issue, this one will be resolved :P
