### ISSUE TITLE
Black screen at start of a biome

### ISSUE THREAD

**Issue by travbp** [Admiral-Billy/Pokerogue-App#27]
Edit: seems to have resolved itself from a cache refresh

Received this black screen at the start of the Fairy Cave biome.

Steam Deck
Release 2.2.1

![image](https://github.com/Admiral-Billy/Pokerogue-App/assets/112346662/e678142f-6bb4-4968-a93b-8107fc76b251)

**Comment by Admiral-Billy** [comment]
Yeah it seems like some asset-related things need a cache reset to properly be downloaded, not sure why. But at the very least, it's an option people can try when needed.
