### ISSUE TITLE
No audio in latest Linux build (steam deck) 

### ISSUE THREAD

**Issue by jackbrookes** [Admiral-Billy/Pokerogue-App#29]
Reproduce
* Download latest Linux build
* Extract
* Add pokerogue file to steam
* edit shortcut to append --no-sandbox
* launch game
* check settings, increase master volume
* no audio

**Comment by Admiral-Billy** [comment]
Hm, I couldn't say why this would be happening; my steam deck seems to have no issues with audio. Any other reports of this?

**Comment by Admiral-Billy** [comment]
Alright, someone else had a similar issue, and they discovered that the Steam Deck's UI sounds were muted because steam was muted, which also translated to muting PokeRogue. Do you have a similar issue?

**Comment by Admiral-Billy** [comment]
I guess without further information, I'll assume this was just a fluke related to what I mentioned or some other odd issue.
