### ISSUE TITLE
Endless mode items not displaying full selection

### ISSUE THREAD

**Issue by Socialblurr** [Admiral-Billy/Pokerogue-App#32]
I'm currently past floor 1400 (started a bit past 1000) and when the item select screen shows  and or I reroll items they will stop displaying a handful of the icons though I can still scroll over to them and read the descriptions. Is this an error on just the offline android version or is this a base Pokerogue issue. It is more prevalent when playing for an extended amount of time without closing the app. If I stop playing for an hour and come back it stops for 20 to 30 floors

**Comment by Socialblurr** [comment]
![Screenshot_20240513_123814_PokeRogue Offline.jpg](https://github.com/Admiral-Billy/Pokerogue-App/assets/136138889/7f71ee4a-4f45-4f84-82c6-2f5b0ff6be5b)

**Comment by Admiral-Billy** [comment]
I think this is just a base PokeRogue issue with it being unoptimized on mobile, I think some sort of memory leak?
