### ISSUE TITLE
Toggle online mode on Android

### ISSUE THREAD

**Issue by maximehuran** [Admiral-Billy/Pokerogue-App#35]
Is it possible to switch between online and offline mode in Android app ?

**Comment by Admiral-Billy** [comment]
It's planned to be a feature at some point, but in the meantime just use the version you get from hitting "install" while on the website (the exact method depends on browser; so just search "install PWA browser-name-here" on Google to see what it says).

**Comment by maximehuran** [comment]
Thank you for you answer !

Unfortunatly it is not possible in Ayn Odin 2 at this moment. I also tried with Firefox.
Also with Daijishō launcher I don't think it is possible.

I build an APK containing the website yesterday and it works, but I cannot disable touch controls (see https://github.com/Admiral-Billy/Pokerogue-App/issues/23#issuecomment-2109449711), and the screen is darker when I press on start, I don't know why. (Maybe the same as https://github.com/Admiral-Billy/Pokerogue-App/issues/34 but in dark, not white)
