### ISSUE TITLE
No controller support

### ISSUE THREAD

**Issue by leonissenbaum** [Admiral-Billy/Pokerogue-App#36]
Unlike the PokeRogue website, controllers don't work on the app (eg: an xbox controller).

**Comment by Admiral-Billy** [comment]
I haven't had any problems with this personally; all of my gamepads are working with it. Are you sure the gamepad support isn't disabled in the settings?

**Comment by leonissenbaum** [comment]
Upon further investigation, it seems like my bluetooth seemed to be dying right as I was testing this, which was bad timing :/ Works now!
