### ISSUE TITLE
Hotkey remapping isn't working

### ISSUE THREAD

**Issue by Sylvaerin** [Admiral-Billy/Pokerogue-App#37]
The remapping function doesn't seem to work for me, even with the setting "Use modified hotkeys" is enabled.

My keymap.json looks like this:

    {
        "W": "Z",
        "A": "Q",
        "S": "S",
        "D": "D",
        "Z": "W",
        "X": "X",
    	"C": "C",
    	"G": "G",
    	"E": "E",
    	"N": "N"
    }

I use an azerty keyboard, so being able to remap would be great!

Thanks in advance.

**Comment by Admiral-Billy** [comment]
Oh yeah you're right, this got broken with the recent update. I fixed this real quick; there may have been a little too much find + replacing with the latest update heh

**Comment by Sylvaerin** [comment]
Bad news: from the rebinding I have done, the "A" key isn't working, rebinding it to something else just disable the key entirely, the original and new one stop working.
It works for the other keys, although I haven't tried the ones I didn't originally rebind.
