### ISSUE TITLE
White screen on Steam Deck since I switched the game back online mode

### ISSUE THREAD

**Issue by Xeronkar** [Admiral-Billy/Pokerogue-App#38]
![image](https://github.com/Admiral-Billy/Pokerogue-App/assets/78463279/f2ea9e3c-10bf-4da5-b664-de7dd057489e)

So yesterday I played normally in offline mode, game was running great.
Today I decided I liked the game enough to go into online mode instead and create an account. But once I disabled Offline mode, I get this white screen (no splashscreen, no loading, nothing).
Console elements shows an empty page (head and body with nothing inside).
I tried wiping both the install folder, cache and %AppData%/Pokerogue files, but even on a fresh install I can't get the game running again.
Any idea what could be wrong ?

**Comment by Admiral-Billy** [comment]
I think at this moment in time the game's servers are just *struggling*; see if this still happens later tonight/tomorrow/etc, or just try waiting for a while, as if you've not properly played online mode the assets are going to take a while to download with the struggling server.

**Comment by Xeronkar** [comment]
Thanks for the answer, I'll give an update tomorrow then.
Is there a log I could check somewhere that would highlight a server issue ?

**Comment by Xeronkar** [comment]
Hello, so I tried re-launching today, and indeed everything is working correctly. I don't know if some kind of error message could be displayed when the game fails to be loaded for future improvements ?
In any case, thanks for the follow-up.
