### ISSUE TITLE
Daily Runs do not load (Windows-Offline)

### ISSUE THREAD

**Issue by Fease57** [Admiral-Billy/Pokerogue-App#40]
Nothing happens after clicking Daily Run and choosing a save (Offline Mode). It just sits on an empty screen and goes nowhere with it. Tried a few times throughout 3 of the latest versions and figured I'd leave a post here about it. I am not sure if anything can be done about it or if you could like click a sync button to connect to the online servers and pull the Daily Run over to Offline Mode everyday. Thanks for your time!

**Comment by Admiral-Billy** [comment]
Update to the latest version of the game files, not just the app.

**Comment by Admiral-Billy** [comment]
For now I'm going to assume that this issue was resolved, although if it wasn't let me know!
