### ISSUE TITLE
Updating PokeRogue to latest build caused save data set-back.

### ISSUE THREAD

**Issue by OddPrograms** [Admiral-Billy/Pokerogue-App#41]
I updated PokeRogue via downloading the Git files and overwriting my folder, this seems to have set my save data back quite a bit... it's strange as it didn't fully reset me but definitely set me back a lot, I also updated PokeRogue via the download offline files after updating, then closed the game and opened it today, repeat launches show the same data loss.

**Comment by Admiral-Billy** [comment]
Unfortunately this seems to be a side effect of a recent change that was pushed to the game; there's not much I can do about this on my end.

**Comment by Entropy86** [comment]
I had the same problem, it completely wiped my offline save. Even if you can't stop it, a warning could be put in the new update to get people to backup session/save before applying the update.

**Comment by tiberazure** [comment]
Yeah, i updated too and i lost everything. All my offline progress got deleted. Entire pokedex which was filled and all the shinies..
Wtf that was insane. Is there a discord for pokerogue modding, cuz i really need to edit some stuff to get back to where i was much faster.

**Comment by Admiral-Billy** [comment]
I am at least *fairly* comfortable in saying this issue should be permanently resolved. Apparently even some affected by this were able to get their data back after more updates too?

**Comment by OddPrograms** [comment]
Can confirm, after an update my save is back (I missed my Stakataka).
