### ISSUE TITLE
feat(android): Add online capability with existing account

### ISSUE THREAD

**Issue by SavGRY** [Admiral-Billy/Pokerogue-App#42]
I've downloaded the APK from the latest release and noticed that there's no online feature. As far as i know you just have to login to get all the progress from your Pokerogue account.

Is there any chance that we can get the same login feature, with also the linked data, also on the APK?

Thanks

**Comment by HerrFrutti** [comment]
Noticed the same.

For now I imported the data from my account. But online access with my actual account woukd be awesome!

**Comment by Admiral-Billy** [comment]
I haven't done it yet because you can just use the PWA version of the app (that you install from the website) for online play, but this is at least a planned feature.

**Comment by SavGRY** [comment]
> I haven't done it yet because you can just use the PWA version of the app (that you install from the website) for online play, but this is at least a planned feature.

Yeah i was going for this approach, but for my device and my setup ([fork of firefox](https://gitlab.com/divested-mobile/mull-fenix) and [fork of bromite for chromium browsers](https://github.com/uazo/cromite)) the PWA just doesn't work, neither do the website, so i was going to install the app and see if there were the same functionality.

No worries by the way, i'm happy to see that will be a planned feature in a future release.

**Comment by Admiral-Billy** [comment]
I did the thing.
