### ISSUE TITLE
Never finished updating 

### ISSUE THREAD

**Issue by MrSipe** [Admiral-Billy/Pokerogue-App#45]
I downloaded the newest version APK and have been trying to open it when opened it says Game files not found so I click update then It just continually says updating game files and never finishes 
On pixel 7

**Comment by Admiral-Billy** [comment]
It might just be taking a long time; for reference there's about 500mb of files it needs to download. That being said, if it still doesn't finish after giving it plenty of time, I'll have to look into this.

**Comment by MrSipe** [comment]
Ok I will

**Comment by MrSipe** [comment]
Your correct I'm impatient lol sorry

**Comment by Admiral-Billy** [comment]
Is ite; I need to add more feedback to the download anyways!
