### ISSUE TITLE
Cannot Win A Run in Offline

### ISSUE THREAD

**Issue by AEPullinger** [Admiral-Billy/Pokerogue-App#46]
I'm currently unable to get a victory in offline mode.  I've tried reloading and reloading + clearing cache, but I keep getting this error.  It seems like it's trying to access the wrong space to update the save file? Unsure.
![image](https://github.com/Admiral-Billy/Pokerogue-App/assets/89876443/22fd446c-daa8-4a85-9414-d519149047ea)

**Comment by Admiral-Billy** [comment]
This one should be fixed if you update your game files to the latest version at the top left I believe.

**Comment by AEPullinger** [comment]
Understood, I'll try that!

**Comment by AEPullinger** [comment]
It worked! Thank you so much, for this and for the awesome app.
