### ISSUE TITLE
MenuBar does not hide with "Auto hide this menu"

### ISSUE THREAD

**Issue by Odizinne** [Admiral-Billy/Pokerogue-App#47]
The MenuBar does not hide as expected when the "Auto hide this menu" option is selected.<br/>
It seems that the cause of this issue may be that settings are being loaded after window creation. 

Additionally, updating the window by simply left-clicking on it hides the menu bar.

**Comment by Admiral-Billy** [comment]
I've noticed a bit of jankiness with it (mostly on Linux), but I'll make sure to fix that particular interaction, thanks.

**Comment by Admiral-Billy** [comment]
Aight, I pushed a fix for this but it's not in the release juuuuuust yet.
