### ISSUE TITLE
The screen freezes after Keldeo changes form as a starter 

### ISSUE THREAD

**Issue by LukrativerLouis** [Admiral-Billy/Pokerogue-App#52]
I’m not sure if this issue is related to the app or the main game.

When I choose Keldeo as a starter and start the run, it changes its form because of its moveset. On Windows, the screen freezes, and on Mac, I get a black screen.

I don’t have a Keldeo in the online version, so I can’t check if it’s an issue with the game or the app. Could you look into this on the app side?

After you refresh that run, which didn’t really start in the first place, it just erases the run, so that doesn’t fix it.

**Comment by Admiral-Billy** [comment]
This does seem to be an issue specifically with my app's offline mode, odd.

**Comment by Admiral-Billy** [comment]
Alright, so this is still partially a bug (the animation doesn't play properly), but in newer versions of the game you can just continue normally instead of it softlocking, so I guess that works?

**Comment by LukrativerLouis** [comment]
Yeah that should todally work, I never cared about the animation, thank you for your work and your fast response :)

**Comment by Admiral-Billy** [comment]
I'll still be looking for the root cause, but at least the pokerogue devs fixed part of the issue on their end heh.
