### ISSUE TITLE
Is there a way to merge save data?

### ISSUE THREAD

**Issue by TheDisturbedDragon** [Admiral-Billy/Pokerogue-App#55]
I've been playing a lot on my online account, but I'm way more advanced on my offline version, with an almost complete pokedex.  The issue is I recently got two shiny legendaries (zacian and Magearna) on the online version, but I can't import the save data without it completely overwriting and locking all my old pokemon.  Is it possible to get a "Merge" option that, for example, lets you mark which pokemon you want to overwrite?  Or just unlocks the ones that would be locked in one save file?.

**Comment by Admiral-Billy** [comment]
There isn't any way to do this as far as I know, at least without really diving into that save file code in the game itself.
