### ISSUE TITLE
Transform Pokémon Type Chart horizontally

### ISSUE THREAD

**Issue by l-dietrich** [Admiral-Billy/Pokerogue-App#57]
Since the included type chart is very helpful, but very hard to read on a small screen (e.g. Steam Deck), I suggest using this type chart which makes better use of screen space.

![type-chart](https://github.com/Admiral-Billy/Pokerogue-App/assets/61526398/2f06cc2c-5bed-45ce-b8ef-267b20d256a8)

**Comment by Admiral-Billy** [comment]
True, that one is a nice one; I'll see if I can include it as an alternative

**Comment by Admiral-Billy** [comment]
I have added it.
