### ISSUE TITLE
Offline mode not working

### ISSUE THREAD

**Issue by Yilangde** [Admiral-Billy/Pokerogue-App#58]
I have a mac computer and the online mode works perfectly.  I download the files for download for offline mode but when I go to the offline option it loads to 100 percent but nothing comes after that. Just the screen background. Any advice?

**Comment by Admiral-Billy** [comment]
This is on the latest version of the app, right?

**Comment by Admiral-Billy** [comment]
For now I'm going to assume this issue resolved itself.

**Comment by AngeredBarbeque** [comment]
I'm having the same issue on my android device.
