### ISSUE TITLE
Parameters don't save when launching on a VM 

### ISSUE THREAD

**Issue by xClaves** [Admiral-Billy/Pokerogue-App#6]
Parameters don't save when launching on a windows VM (didn't try others).
Maybe adding a save file to handle this ?

**Comment by Admiral-Billy** [comment]
I assume you're talking about the settings in the menu? If so, it should already be using a save file I think, in the appdata folder somewhere. If you're talking about something else though please clarify!

**Comment by xClaves** [comment]
Yes i was talking about the settings on the menu where you change speed, language...
I can indeed see the file named Preferences on appdata, but it doesn't seem to be read or updated (on both normal windows and vm windows but for a reason settings are kept on normal windows but not in the VM). I tried to delete this file on normal windows to see if it would erase my settings and it didn't.

**Comment by Admiral-Billy** [comment]
As far as I can tell, it should be reading from the settings.json that is created in that same directory. I can confirm that it exists on my OS at least; maybe VMs don't create it properly?
![image](https://github.com/Admiral-Billy/Pokerogue-App/assets/72857839/192694ee-6ad9-46f0-852b-7159991f1777)

**Comment by Admiral-Billy** [comment]
> Yes i was talking about the settings on the menu where you change speed, language...

Oh I just read this part. As far as I know this is just an issue with PokeRogue itself, where occasionally it'll forget your settings. It does that for me in both the browser and the app version; maybe it's just related to the appdata cache getting cleared or something?

**Comment by xClaves** [comment]
I've installed the last update and for now everything is working well.
