### ISSUE TITLE
login problem

### ISSUE THREAD

**Issue by RareDoggo** [Admiral-Billy/Pokerogue-App#60]
when i try to login on both desktop app and browser app i get a error message (tried to redownload the game few times)
![PokeRogue_Q5TeWrNMjE](https://github.com/Admiral-Billy/Pokerogue-App/assets/170689006/1ae35dd1-2a11-45ad-8041-8c91b39f61d7)

**Comment by Admiral-Billy** [comment]
The servers are down for now because of a DDOS attack.

**Comment by RareDoggo** [comment]
thank u :3
