### ISSUE TITLE
Can't see the keyboard on the Android

### ISSUE THREAD

**Issue by Liu7i-67** [Admiral-Billy/Pokerogue-App#61]
# Device information
Processor: Snapdragon 8 Gen2
Android Version: 14
RAM: 12GB
Device Model: MEIZU 20 Pro
Device Type: M391Q
![image](https://github.com/Admiral-Billy/Pokerogue-App/assets/95481822/86a266f5-a965-4575-88ec-920780cdc6e4)

# Problem description
Can't see the keyboard on the Android
> I have tried clearing the cache files in the android/data/com.example.pokerogue/files/game directory, but it did not work.

![image](https://github.com/Admiral-Billy/Pokerogue-App/assets/95481822/23489b99-29da-4029-891c-e493a8885b31)

**Comment by Admiral-Billy** [comment]
Oh that's odd, it must not be detecting your device as a mobile device or something. I haven't been able to recreate that issue myself, but if you have a bluetooth controller or something you might be able to get to the menu and turn those on?

**Comment by Liu7i-67** [comment]
ok，ty
