### ISSUE TITLE
Hey I was accessing Offline Mode in windows and the thing is stuck at a white screen

### ISSUE THREAD

**Issue by RADICALDRAKE** [Admiral-Billy/Pokerogue-App#63]
Why is Pokerogue offline just stuck at a white screen?

**Comment by Admiral-Billy** [comment]
That's usually a sign that the files didn't download properly or didn't finish downloading; make sure to let it completely finish.

**Comment by CartucheraSB** [comment]
Hey so, same thing is happening to me, when I try to download the latest files for offline it starts downloading and near the end it stops working. When I checked in the console it seems like im missing the "index.html" file so maybe thats your problem as well? I dont know where or how I should get that file tho.

**Comment by Admiral-Billy** [comment]
Are you sure it actually stopped working at the end? The extraction can take quite a while, especially if an anti-virus is scanning all of the files.

**Comment by RADICALDRAKE** [comment]
> That's usually a sign that the files didn't download properly or didn't finish downloading; make sure to let it completely finish.

Never Mind It works the extraction just took some time.

**Comment by Admiral-Billy** [comment]
If it took longer than a minute or two, it's a known issue that sometimes Windows Defender or similar will slow it down to a crawl as it scans each and every little file; this is something that modders have had to deal with for years in lots of other games heh

**Comment by CartucheraSB** [comment]
> Are you sure it actually stopped working at the end? The extraction can take quite a while, especially if an anti-virus is scanning all of the files.

In my case yes, windows tells me it stopped working

**Comment by Admiral-Billy** [comment]
Then yeah that's just a case where you have to be extra patient, and consider adding an exception in windows defender/temporarily disabling it so it works faster.

**Comment by CartucheraSB** [comment]
Thx for the help, adding the exception worked!

**Comment by Admiral-Billy** [comment]
Alright cool, I'll add a note about that in the readme.
