### ISSUE TITLE
Newest apk can't load files

### ISSUE THREAD

**Issue by GameOverFlowChart** [Admiral-Billy/Pokerogue-App#67]
The newest apk (Initial Installer + Droid Drip) can't load the online data but older apk versions can.

![Screenshot_2024-05-28-00-22-23-75_e24bb2268d29b145a4551512760a7a8b](https://github.com/Admiral-Billy/Pokerogue-App/assets/109205200/19e4a8ca-ab40-4bd6-a809-242b48b949b4)

**Comment by Admiral-Billy** [comment]
So you're trying to play online here and it isn't working? Just to clarify.

**Comment by Admiral-Billy** [comment]
Oh I see what weirdness is going on here. For some reason android *hates* showing the 100% completion for the game file download, and I have no idea why. Literally when I go into the code and cap the update message to only show from 0% to 99%, it works, so uh, I guess that's what I'm going to do.

**Comment by Admiral-Billy** [comment]
I'll go ahead and edit the current release with a hotfix for this issue.

**Comment by GameOverFlowChart** [comment]
> So you're trying to play online here and it isn't working? Just to clarify.

Sry for the late answer, I was trying to update for offline play. I will leave feedback here once I tried the fixed version.

**Comment by GameOverFlowChart** [comment]
> I'll go ahead and edit the current release with a hotfix for this issue.

I can confirm that the fix worked
