### ISSUE TITLE
App for Android 10

### ISSUE THREAD

**Issue by Zainimarz** [Admiral-Billy/Pokerogue-App#68]
Please make the app work on android 10 as well, my phone is a bit old but I can't afford to buy a new one right now

**Comment by Admiral-Billy** [comment]
I tested it and PokeRogue itself doesn't even work on lower Android versions, not just the app. There's not a whole lot I can do here :(

**Comment by Zainimarz** [comment]
It runs completely fine, on my phone realme 5i with snapdragon 665 and
4gigs of ram

**Comment by Admiral-Billy** [comment]
Apparently it's just the android *emulators* that struggle there, although there's still a hard cutoff somewhere. I haven't been able to figure out how to reduce the Android version yet because I don't have actual devices to test it on, but I'll leave it on the radar at least.

**Comment by Zainimarz** [comment]
Ok, thanks for the update.

**Comment by Admiral-Billy** [comment]
Can you give this version of the app a test? I may have fixed the issue.

[app-debug.zip](https://github.com/user-attachments/files/15543164/app-debug.zip)

It's an apk inside of a zip, so just extract it and install/update with it.

**Comment by Zainimarz** [comment]
Ok I'll give this a try when I get home

**Comment by Zainimarz** [comment]
Updating the offline files results in time out error, the online function
works but takes way too long to load

**Comment by Admiral-Billy** [comment]
Oh I see, I'd keep trying again with the offline download; the timeout should be about 3 seconds for a connection. If that still doesn't work, try this version with a longer timeout and see if that helps at all.

[app-debug.zip](https://github.com/user-attachments/files/15570913/app-debug.zip)

**Comment by Zainimarz** [comment]
Good news, i was able to play the offline version with this one, but
downloading the debug mode still gets the timeout error

**Comment by Admiral-Billy** [comment]
Ah, I see. I'm going to close this issue for now since I *think* it's just internet-related? But at least you've got a solution that mostly works here. Feel free to open it up again if you think it's something else though.
