### ISSUE TITLE
Error when downloading the latest files for offline

### ISSUE THREAD

**Issue by travbp** [Admiral-Billy/Pokerogue-App#69]
Stops with the same installation  progress each time.

Steam Deck
Release 2.2.1

Edit: may have just been my Wi-Fi connection, since it worked on my hotspot

![image](https://github.com/Admiral-Billy/Pokerogue-App/assets/112346662/b016e4da-5570-444e-b530-da14623fa6ac)

**Comment by Admiral-Billy** [comment]
I'll close the issue for now then; that error looks like a spotty connection to me (since it's about connection resets). That being said, if it happens consistently for some reason feel free to reopen this with more details.
