### ISSUE TITLE
Start Fullscreen setting or launch argument

### ISSUE THREAD

**Issue by Odizinne** [Admiral-Billy/Pokerogue-App#7]
It would be great to have this, especially for couch gaming (I add everything to steam to be able to start it trough big picture)!

something like pokerogue --fullscreen would be nice

**Comment by Admiral-Billy** [comment]
Yeah that's easy enough for me to do, I'll see if I can just have it remember your last setting for the size.

**Comment by Admiral-Billy** [comment]
Alright, the latest version of the app just generally remembers your window size/fullscreen status/maximized status, so let me know if this does the trick!

**Comment by Odizinne** [comment]
I was planning to add a -f arg, but i'll test your changes right now!

**Comment by Odizinne** [comment]
Not related to this issue, but it seems like menubar is opened by default. A click in the main window is required to hide it.

Settings saving is working like a charm!

**Comment by Admiral-Billy** [comment]
Yeah, I switched the default behavior to just stay open, and let users hide it if they wish; helps me avoid having to tell everyone to hit Alt for the menu heh.
