### ISSUE TITLE
Client Window Changes Position On Refresh

### ISSUE THREAD

**Issue by BlueSkySM** [Admiral-Billy/Pokerogue-App#70]
I have the window snapped to half my screen in Windows, but whenever I refresh the page with the CTRL+R or F5 buttons, it changes the size of the window and puts it at the center of my screen again. Is this something you can change or is this on my end? 
![image](https://github.com/Admiral-Billy/Pokerogue-App/assets/79213590/31029345-e5c5-4e8e-a0e3-ede9c6ad6530)
![image](https://github.com/Admiral-Billy/Pokerogue-App/assets/79213590/46e2ecd2-1a40-4761-aaa5-b4f4b23b8369)

**Comment by Admiral-Billy** [comment]
Oh yeah, I forgot about that one; I can fix that pretty easily (and have done so).

**Comment by BlueSkySM** [comment]
Thank you!!!!!
