### ISSUE TITLE
Sound doesn't work when playing the game on steam deck (not desktop)

### ISSUE THREAD

**Issue by acssimpson** [Admiral-Billy/Pokerogue-App#71]
It *does* work when playing it on the desktop mode, but not when you switch to steamdeck's native boot mode.

**Comment by Admiral-Billy** [comment]
Do you have Steam's UI sounds enabled? For some reason those are tied together with the game's volume, and others have reported a similar issue.

**Comment by HitchEdits** [comment]
> Do you have Steam's UI sounds enabled? For some reason those are tied together with the game's volume, and others have reported a similar issue that was fixed by enabling those sounds.
> 
> I can at least confirm my OLED Steam Deck has no problems with sound in gaming or desktop mode.

I've been playing on the non-OLED steam deck and had no issue with sound, just to eliminate that factor for you.

**Comment by acssimpson** [comment]
I have double checked all of the sound options, but the steam deck is heavily layered enough with configuration layers that I would believe it's on my end. 

I'll figure it out and report back.

**Comment by acssimpson** [comment]
If it's not a steam deck problem in general, then it must be local. I'll figure it out then! Thanks for the reply (and the great app)
