### ISSUE TITLE
App size smaller

### ISSUE THREAD

**Issue by GameOverFlowChart** [Admiral-Billy/Pokerogue-App#75]
It's stated that the last version (A Smidegon O' Service) just has bug fixes, but the apk is now half the size. That's a good thing of course, maybe because of updated dependencies or compiler or something but I thought you should know this in case you didn't notice.

**Comment by Admiral-Billy** [comment]
I did notice the reduced file size, but yeah it should be pretty much the same app as far as I know. That being said let me know if it seems like something is missing that shouldn't be.
