### ISSUE TITLE
Fix Obtanium release versioning.

### ISSUE THREAD

**Issue by Trinangle** [Admiral-Billy/Pokerogue-App#79]
Hi there.

I love the work you are doing to port this to mobile.
Consequently I set up Obtanium to automatically update the app off of github.

This doesn't work perfectly for one main reason.
Github states the release version.
As of making this it is stated to be: 2.4.1
However the APK when installed is listing itself as 1.0

I believe the fix should simply be to include the versioning within the APK but am not entirely sure.

This is not an important request would just be a nice to have for auto updating purposes.

Thanks very much for your time and effort.
![Screenshot_20240603-221532_Obtainium](https://github.com/Admiral-Billy/Pokerogue-App/assets/97986514/07e57813-5fb4-4601-9125-08c76f31bec6)

**Comment by Admiral-Billy** [comment]
Oh yeah, that's easy enough to do. I'll have that done for the next apk release whenever that is.
