### ISSUE TITLE
[FEAT] Add a setting to hide mouse cursor

### ISSUE THREAD

**Issue by Odizinne** [Admiral-Billy/Pokerogue-App#8]
This would be beneficial for controller gaming<br/>
I think the correct behavior is still to show the cursor by default

**Comment by Admiral-Billy** [comment]
I did the thing.
![image](https://github.com/Admiral-Billy/Pokerogue-App/assets/72857839/669f0381-5880-4a39-ac52-794aa6b8b1fe)
