### ISSUE TITLE
Can't open it on mac

### ISSUE THREAD

**Issue by Osheyking** [Admiral-Billy/Pokerogue-App#80]
it just won't open when i try it closes straight away

**Comment by Admiral-Billy** [comment]
What mac do you have, and is it showing any kind of popup window?

**Comment by Osheyking** [comment]
macbook air on sonoma with m1 chip and it show dose show anything when i clikc to open it

**Comment by Admiral-Billy** [comment]
That should be mostly fine, although the permissions could be an issue. After you've extracted it, try holding ctrl while clicking to open it and then click open again, and that'll let you run it even though Apple doesn't trust me because I don't pay them heh

**Comment by Osheyking** [comment]
nothing happens when i click it

**Comment by Admiral-Billy** [comment]
You are trying to run the app right? If you just run the zip, it'll extract it and open Finder so you can open the actual app. I'm not being given a lot of information here so it's pretty hard for me to tell what's going on.

**Comment by Osheyking** [comment]
i unziped it up and when i click it nothing happens

**Comment by Admiral-Billy** [comment]
Can you share a screenshot or video or something? I'll have to have more information than this unfortunately.

**Comment by Osheyking** [comment]
i will later i can't rn
