### ISSUE TITLE
Option to make the Android touch screen controls disappear when a physical controller is detected

### ISSUE THREAD

**Issue by TheExcitedTech** [Admiral-Billy/Pokerogue-App#81]
Thanks for developing this app, it has made the game accessible for me to play on my android gaming device!

Device: Retroid Pocket 4
Android Version: 13
Latest Version of Pokerogue-App

I believe this is a bug because there is a touch screen settings that will not toggle off for me. OR, it's not supposed to go opaque. 

The biggest gripe is that it puts an opaque white filter on the game and I don't think there is a way to remove the controller filter from the screen. 

Here are some screenshots attached. 

The first two are using touch screen controls. This is not touching the physical keys at all.

![1](https://github.com/Admiral-Billy/Pokerogue-App/assets/61395251/eadb3112-bea1-4c8d-9b15-3bffe37ab5d7)
![2](https://github.com/Admiral-Billy/Pokerogue-App/assets/61395251/db2c1270-ca64-4139-bdd1-924e09f2e59f)

When **any** physical key is pressed then the opaque filter comes on

![3](https://github.com/Admiral-Billy/Pokerogue-App/assets/61395251/8d12871a-30be-4800-9846-507a6f1cca97)

Physical keys are detected, but that filter just doesn't go away unless you fully quit the app and _only_ use touch controls and _never_ touch the physical keys.

**Comment by Admiral-Billy** [comment]
This is an issue that needs to be fixed on the game devs' end I believe, see #23 and #34
