### ISSUE TITLE
Api error

### ISSUE THREAD

**Issue by KillerDogeEmpire** [Admiral-Billy/Pokerogue-App#83]
I am running android 14 on my new phone and when trying to get the latest official files, or sign in using account save, I get an error of downloading the files

**Comment by KillerDogeEmpire** [comment]
Here is t
![Uploading Screenshot_20240604_173207_PokeRogue Offline.jpg…]()
he exact error

**Comment by KillerDogeEmpire** [comment]
Here is the exact error
![Screenshot_20240604_173207_PokeRogue Offline](https://github.com/Admiral-Billy/Pokerogue-App/assets/87155550/9b645743-7881-41a1-83f5-f9f1e6a4e329)

**Comment by KillerDogeEmpire** [comment]
also happens with futaba build

**Comment by Admiral-Billy** [comment]
I think GitHub may have been down or something for a minute, but if it's still happening try updating the app with the latest version from the releases to see if that helps.

**Comment by KillerDogeEmpire** [comment]
The latest update fixed it

**Comment by Admiral-Billy** [comment]
Seems that the real cause of this was my API key expiring; this means an app update is actually *mandatory* for people to use the offline mode of the app now.
