### ISSUE TITLE
Adroid Export Data Issues

### ISSUE THREAD

**Issue by Strontoria** [Admiral-Billy/Pokerogue-App#85]
Whevener I attempt to export data or session data on the latest apk version (published yesterday June 4th) I get a message tellimg me it was successfully exported to the download folder, but no file appear.

**Comment by Admiral-Billy** [comment]
What Android version are you on? I wasn't able to test anything below 11 to see if that works correctly.

**Comment by Strontoria** [comment]
I'm running Android version 14 on a Pixel 5.  The app runs perfectly in every other way as far as I can tell.

**Comment by Admiral-Billy** [comment]
Oops, I did in fact mess something up. I've updated the latest release with a patched version that fixes this.

**Comment by Strontoria** [comment]
Thank you so much!  I really appreciate the ongoing time and expertise you put into this app.
