### ISSUE TITLE
Bug: Objects disappearing?

### ISSUE THREAD

**Issue by Leavesoftrees** [Admiral-Billy/Pokerogue-App#89]
Android app, offline play : Objects in the shop keep disappearing. A random number of object sprites disappear / do not load, consistently, 1 to 4 objects at a time.

 I'm not aware to what extent it might be a bug coming from pokerogue itself or not. Text still loads when you select them, it seems to only be the sprite not loading. Not a major issue at all, just wanted to signal it as a consistent bug, at least on my device (samsung A22, android 13).

Thx for all the good work, cheers!

**Comment by Admiral-Billy** [comment]
As far as I know, this is just a bug with PokeRogue itself just having some sort of memory leak on mobile. It's definitely annoying though.
