### ISSUE TITLE
Not being able to download the files for offline

### ISSUE THREAD

**Issue by Savagepro9055** [Admiral-Billy/Pokerogue-App#90]
So for some reason, when I try to download the files, it just keeps "updating game files"
![Screenshot_20240616_192434](https://github.com/Admiral-Billy/Pokerogue-App/assets/86777765/a08570e2-38f0-4659-86b8-67866e9b3667)

**Comment by Savagepro9055** [comment]
This is on Android btw

**Comment by Admiral-Billy** [comment]
What kind of internet speeds do you have, and how long are you waiting? There's a few hundred MB of files being downloaded so it might take a while.

**Comment by MangoDaemon** [comment]
I am having thr same, or at least a similar problem. When I hit download offline files, It is also stuck at downloading files, I kept an eye on my phone for about an hour and a half before going to sleep and the app was closed when I woke back up. Now when I tab out of the app I get a timeout error from pokerogue about 30 seconds after starting the download. If I do not tab out, I get no error and the app seems to close after 2 to 3 hours of downloading

**Comment by MirhasVida** [comment]
Me either

**Comment by ElviraTjandra** [comment]
I have the same problem

**Comment by ShaypValentine** [comment]
I'm having the same problem I usually update every two day to be sure not to miss any change but since last week end I get this error.
![1000024949](https://github.com/Admiral-Billy/Pokerogue-App/assets/83609644/b2762ae5-493c-40f5-b8ef-8a70b9f3e001)

**Comment by MangoDaemon** [comment]
Update on my own situation, while babysitting I kept pokerogue open and updating without letting the screen turn off or tabbing out for like 30 minutes and then it worked

**Comment by drjoebofa** [comment]
@MangoDaemon Are you using an android device? Or was this on PC/Mac?

**Comment by Admiral-Billy** [comment]
> Just wanted to add that I believe I'm having the same issue on Android. When attempting to use the "Update to Latest Official Files for Offline" OR "...or Download Futaba's Build" options, I get the following error pop-up on the device:
> 
> "Failed to update game files. Error: https://api.github.com/repos/Admiral-..."
> 
> Seems like device permissions or some kind of routing issue may be preventing the app from accessing the offline files as intended.

Update the app from Github. That issue happens on the previous version of the app because the API key I used in it expired.

**Comment by MangoDaemon** [comment]
> @MangoDaemon Are you using an android device? Or was this on PC/Mac?

Android, on pc the download only took like 15 minutes, and the progress bar was nice to see thar something is actually happening, something like that would go a long way on mobile

**Comment by drjoebofa** [comment]
@Admiral-Billy Thanks! I had been downloading what I thought was the most recent .apk but I must've been confused. My apologies. Everything seems to be working now. 

Thank you again for all your hard work on this project! Very much appreciated. :)

**Comment by MirhasVida** [comment]
Thx! Solved
