### ISSUE TITLE
Not able to start game if starter cost isn't 10

### ISSUE THREAD

**Issue by EnriqueJuspi** [Admiral-Billy/Pokerogue-App#91]
Some pokemon might have decimal cost like 0.50 or 0.25 after the cost reduction. In PC, you can press 'Enter' to start the game even when the starter cost is less than. In Mobile, you can only start the game if your cost is exactly 10.

**Comment by Admiral-Billy** [comment]
You can still scroll to the bottom and hit the "start" button there to start the run.

In either case, this is not something specific to my app.

**Comment by EnriqueJuspi** [comment]
Thanks for replying, seems like the issues appear on an older version. The
issue is gone after i updated into the latest version.
