### ISSUE TITLE
How to package to get the latest files？

### ISSUE THREAD

**Issue by Liu7i-67** [Admiral-Billy/Pokerogue-App#92]
Hello, I'd like to ask a question.

I used the Windows version of the program you packaged, and it runs normally in offline mode.

I want to get the latest game files since there were some updates on June 8th.

So, I cloned the official repository and modified `src/battle-scene.ts` to set `bypassLogin` to always be `true`.

The packaged files work fine when accessed through a server proxy, but they don't run properly when used with the Windows program wrapper.

Like this:
![Snipaste_2024-06-09_18-06-16](https://github.com/Admiral-Billy/Pokerogue-App/assets/95481822/45742d74-2af3-42c8-81fa-c1c05b9eabf0)

The error message is as follows:
![image](https://github.com/Admiral-Billy/Pokerogue-App/assets/95481822/0733a3bf-40df-4770-be1f-e415fb619bb7)

I am very certain that these two files exist:
![image](https://github.com/Admiral-Billy/Pokerogue-App/assets/95481822/da1691fd-d952-44b4-8cf6-1d856cfef6f1)

What other modifications do I need to make?

Thank you very much

**Comment by DoctorGoat** [comment]
You can run the official version in offline mode. Follow the compilation instructions and then run the game with npm run start:dev. press... C? I think? to launch a browser or just open localhost:8000 in a browser.

**Comment by Admiral-Billy** [comment]
You also need to modify the index.html to use a relative path when searching for those. Modify the "/assets/index-whatever.js" and the line below it to be "./assets/index-whatever.js", otherwise it can't find the files.

**Comment by Liu7i-67** [comment]
> You also need to modify the index.html to use a relative path when searching for those. Modify the "/assets/index-whatever.js" and the line below it to be "./assets/index-whatever.js", otherwise it can't find the files.

ok，Thank you very much！

**Comment by Admiral-Billy** [comment]
I'll assume you're good to go for now and close this issue.
