### ISSUE TITLE
Android Export Issue Notice

### ISSUE THREAD

**Issue by NFSNOOB** [Admiral-Billy/Pokerogue-App#93]
More a Hint then an issue. Maybe you can write the information down somewhere.
I had the problem too with the data export on Android. After updating offline data + Github app release, I enabled the settings but the file export was still not working.

I needed to restart my phone and only then the export was working. I have only PWA experience so maybe some cache with old data was used that still prevent export? Just to let you know.

Sorry if it is spam for you.

**Comment by NFSNOOB** [comment]
Actually the export seems to work only once after phone restart.
Phone: Google Pixel 7
Anroid version: 14

**Comment by Admiral-Billy** [comment]
Oh that's odd. Thanks for letting me know!
