### ISSUE TITLE
App now asks to access all files on Android

### ISSUE THREAD

**Issue by GameOverFlowChart** [Admiral-Billy/Pokerogue-App#94]
This is usually not the intended way of doing things on Android. Maybe you needed this permission for older Android versions but it's not good practice for actual Android app. The permission to access all files is intended for apps like file managers, it's a security risk (you don't want all your files on your phone to be deleted because of a bug in an app with that permission, or random files and folders in random locations on your phone without knowing where they come from) and the app shouldn't really need it (it did work before without needing it). Apps which ask for this permission are even restricted on the Playstore  as far as I know. In short it's the wrong way of handling files on Android if the app isn't a file manager, I myself suggest to users to never give this permission to an app which has online access.

**Comment by GameOverFlowChart** [comment]
Oh wow, according to the app, the game files were updated successfully despite me not giving the permission, and despite the error message that the permission is needed.

**Comment by GameOverFlowChart** [comment]
And it's really annoying that it ask for the permission at every app start.

**Comment by Admiral-Billy** [comment]
I recognize that it's not a good practice, but it's needed on *some* devices for the updater, and is also needed for in-game importing/exporting.

**Comment by GameOverFlowChart** [comment]
> I recognize that it's not a good practice, but it's needed on _some_ devices for the updater, and is also needed for in-game importing/exporting. It's also never going to be on the Play Store.

It might be possible to check for device version  before asking or at least ask for permission before the download instead of every app start which on its own is also better practice.
