### ISSUE TITLE
Please add a confirmation message on the "delete offline files" button.

### ISSUE THREAD

**Issue by Fuyuki69** [Admiral-Billy/Pokerogue-App#95]
I accidentally fat fingered the "delete offline files" button and lost about a month of progress. I wouldn't be surprised if others also have done this or will do it in the future even though not many play offline from what I can see. So please just add a confirmation message upon tapping that button.

**Comment by Admiral-Billy** [comment]
Delete offline files is referring to the game files, not your save files. Your saves should be perfectly fine as long as you go redownload the game.

**Comment by Fuyuki69** [comment]
I tried that a few times and thought it wouldn't work since the download was taking a lot longer than before but I just now tried it again and it downloaded after like 40 minutes and my save is still fine. So, thanks for the help. Though I still feel like there should be a confirmation message for hopefully obvious reasons.

**Comment by Admiral-Billy** [comment]
Yeah that's fair, it probably should have a confirmation anyways.

**Comment by IceburgLettuce17** [comment]
For me I can't download it at all, it pops up with a "Index 1 out of range [0..1)" error

**Comment by IceburgLettuce17** [comment]
(after deleting offline files accidentally)
