### ISSUE TITLE
Flip5 display resolution issue

### ISSUE THREAD

**Issue by hojjung** [Admiral-Billy/Pokerogue-App#96]
![Screenshot_20240613_134706_PokeRogue Offline](https://github.com/Admiral-Billy/Pokerogue-App/assets/38466541/5c7454e9-f092-41c5-9686-80ab29504568)

Thx for made Apk but we need

Larger display resolution 

This is painful

**Comment by Admiral-Billy** [comment]
This is a PokeRogue issue unfortunately; try playing with the phone rotated horizontal instead and that might work out better.
