### ISSUE TITLE
Save issues in offline mode

### ISSUE THREAD

**Issue by AveragePKMN** [Admiral-Billy/Pokerogue-App#97]
Whenever i close the pokerogue app in offline mode when i reopen it everything is reset including my settings and game saves.

**Comment by Admiral-Billy** [comment]
This usually means that there's some version of PokeRogue lingering in the background; try closing it out in task manager or restarting the PC and it'll go away and be able to load your saves again.

**Comment by AveragePKMN** [comment]
I think it worked. I tested it and when i closed and reopened offline mode it didn't delete my files
