### ISSUE TITLE
Failed to download game files: Index 1 out of range [0..1) on mobile (Offline Mode)

### ISSUE THREAD

**Issue by IceburgLettuce17** [Admiral-Billy/Pokerogue-App#98]
What OS are you on? 
Android 10.0

How do I reproduce this bug:
- Delete offline files, but exit out of the application
- If done correctly, game will no longer load, but when trying to redownload, comes up with an error.

**Comment by IceburgLettuce17** [comment]
(only on futaba's build)

**Comment by Admiral-Billy** [comment]
Yeah there was a small issue with the game file repo not properly uploading her build, it should be fixed here in just a bit once I figure it out.
